Documento para mapear todo el código de Varanini

ECG -> 60000x4 (4canales 60000 muestras) 1000Hz
* Artifact Canceling
    % ---- Artifact canceling ----
    % X=FecgFecgImpArtCanc(ECG,fs,cName,graph,dbFlag);
    X=FecgImpArtCanc(ECG,fs,cName,0,0);
** % Impulsive artifact removal from each ECG channel,
   % applying the function "ImpArtElimS" to each channel.
   
Median filter -> Implementation

** liquid-dsp -> c++ library
** aquila -> c++ library
** spuc -> c++ library
** libc, libm, fftw -> c libraries
** Digital filters -> github.com/vinniefalco/DSPFilters -> c++ library


* Detrending
%   ECG detrending
%
%  A baseline signal is estimated applying a low pass Butterworth filter 
%  in forward and backward direction.  The filter cut frequency is 3.17Hz. 
%  Each detrended signal is obtained as difference between the original signal 
%  and the estimated baseline. 
%  In case of residual artifacts due to fast baseline movements, median filtering is used.

* Power Line interference removal by notch filtering
  % Analize el espectro en frecuencia para determinar si aplica un notch a 50Hz o a 60 Hz. y despues lo aplica zero phase filter
% Notch filter


* Independent Component Analysis
% -----------------------------------------------------------------------------------
%   Fecg: Independent Component Analysis for mother ecg separation
%   Fixed point algorithm of Hyvarinen with deflationary ortogonalization is applied.
%   In a first attempt the hyperbolic cosine as contrast function is used because it 
%   produces more robust estimates. In case of failure of convergence the algorithm 
%   was run a second time using the kurtosis.
FastICA, Hyvarinen ()

** LibICA

* Signal Interpolation
Interpolacion de la señal usando fft

fftw-> Convertir a fft y luego conversion inversa con mas puntos.

* Channel selection and mother QRS detection
%   Fecg: "Mother" QRS detection
%  - Best mother ECG selection based on a priori information on mother ECG pseudo-periodicity.
%    A raw derivative filter signal obtained as the difference between 
%    the average values on two intervals of 7ms far off 9ms)
%  - The absolute value of the raw derivative signal was filtered by a forward backward 
%    Butterworth bandpass filter (6.3-16.Hz).
%  - mother QRS detection based on this absolute derivative
%
% Tambien QRS detector

* Mother QRS cancelling

% ---------------------------------------------------------------------------------------------
% Fecg: "Mother" ECG canceling using  PQRST approximation obtained by 
% Singular Value Decomposition (SVD).
% A trapezoidal window is used to select and weight the signal around each detected mother QRS.
SVD implementacion C: Probably CLAPACK -> 
gams.nist.gov 
www.netlib.org

* Source separation by ICA on residual signals

%   Fecg: Fetal ecg enhancement by ICA
%   Fixed point algorithm of Hyvarinen with deflationary ortogonalization is applied.
%   In a first attempt the hyperbolic cosine as contrast function is used because it 
%   produces more robust estimates. In case of failure of convergence the algorithm 
%   was run a second time using the kurtosis.


* Channel selection and Fetal QRS detection


    
    % ---- detrending  ----
    % Xd=FecgDetrFilt(X,fs,cName,graph,dbFlag);
    Xd=FecgDetrFilt(X,fs,cName,0,0);
    
    % ---- Power line interference removal by notch filtering ----
    % Xf=FecgNotchFilt(Xd,fs,cName,graph,dbFlag);
    Xf=FecgNotchFilt(Xd,fs,cName,0,0);
    
    % ---- Independent Component Analysis ----
    % Xm=FecgICAm(Xf,fs,cName,graph,dbFlag,saveFig);
    Se=FecgICAm(Xf,fs,cName,graph,dbFlag,saveFig);
    
    % ---- Signal interpolation
    % Xi=FecgInterp(X,fs,interpFact,cName,graph);
    [Se,fs]=FecgInterp(Se,fs,4,cName,0);
    
    % ---- Channel selection and Mother QRS detection
    qrsM=FecgQRSmDet(Se,fs,cName,graph,dbFlag,saveFig,qrsAf);
    
    % ---- Mother QRS cancelling
    Xr=FecgQRSmCanc(Se,qrsM,fs,cName,graph,dbFlag,saveFig,qrsAf);
    
    % ---- Source separation by ICA on residual signals
    Ser=FecgICAf(Xr,fs,cName,graph,dbFlag,saveFig);
    
    % ---- Channel selection and Fetal QRS detection
    % qrsF=FecgQRSfDniAdf(Ser,fs,cName,qrsM,graph,dbFlag,saveFig,saveFigRRf,qrsAf);
    qrsF=FecgQRSfDet(Ser,fs,cName,qrsM,graph,dbFlag,saveFig,saveFigRRf,qrsAf);
    
    fetal_QRSAnn_est=qrsF;
    QT_Interval         = [];
%---------------------------------------------------------------------------------------------
%   Fecg: Fetal QRS detection
%   - For each ECG channel:
%     - Fetal QRS pre-detection
%     - Identification of a good interval
%     - Fetal QRS detection in forward direction starting from the beginning
%       and in backward starting from the end of such a interval
%   - Best fetal QRS detection selection based on fetal RR variability and
%     fetal-mother QRS position coincidence
